# name: CI

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]


# jobs:
#   build:
#     runs-on: ubuntu-latest
#     if: github.repository == 'ayushmishra2005/substrate-barcode-scanner'
#     name: Auto Build CI

#     steps:
#       - name: Checkout repo
#         uses: actions/checkout@v2
#         with:
#           token: ${{ secrets.SECRET_NAME }}
        
#       - name: Install toolchain
#         uses: actions-rs/toolchain@v1
#         with:
#           toolchain: nightly
#           target: wasm32-unknown-unknown
#           override: true
#           default: true
#           components: rustfmt, clippy
          
#       - name: Check Test
#         run: |
#           cargo test

#       - name: Create comment
#         if: steps.fc.outputs.comment-id == ''
#         uses: peter-evans/create-or-update-comment@v1
#         with:
#           issue-number: ${{ github.event.pull_request.number }}
#           body: |
#             /benchmark runtime substrate pallet_barcode_scanner
#           reactions: rocket
        
#       - name: Check Benchmarking
#         run: |
#           cargo build --release --features runtime-benchmarks
          
#       - name: Update Weights
#         run: |
#           ./target/release/node-template benchmark --chain=dev --execution=wasm --wasm-execution=compiled --pallet=pallet_barcode_scanner --extrinsic='*' --steps=50 --repeat=20 --heap-pages=4096 --template=./frame-weight-template.hbs --output=./pallets/barcode-scanner/src/weights.rs
        
#       - name: Commit changes
#         uses: EndBug/add-and-commit@v7
#         with:
#           author_name: ayushmishra2005
#           author_email: ayushmishra2005@gmail.com
#           message: 'Updated weights'
#           add: '*.rs'
